name: app_hotel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  expandable_text: ^2.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  photo_view: ^0.15.0
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  image_picker: ^1.1.2
  firebase_storage: ^12.0.1
  parse_server_sdk_flutter: ^8.0.0
  gap: ^3.0.1
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  firebase_database: ^11.0.1
  animated_bottom_navigation_bar: ^1.3.3
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.7.0
  geocoding: ^3.0.0
  firebase_auth: ^5.1.0
  carousel_slider: ^4.2.1
  flutter_animate: ^4.5.0
  rename: ^3.0.2
  animated_text_kit: ^4.2.2
  provider: ^6.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/login.png"  # Certifique-se de ter uma imagem no diretório assets
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
  - lib/images/
  - assets/icon/logo.png
  - assets/icon/login.png
