// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPaGkzO8CxTeXKcUopp-zIaSmhGBPatos',
    appId: '1:476261170587:web:41a46f4ea3d672fd3b753e',
    messagingSenderId: '476261170587',
    projectId: 'vidabrasilapp-cfab9',
    authDomain: 'vidabrasilapp-cfab9.firebaseapp.com',
    storageBucket: 'vidabrasilapp-cfab9.appspot.com',
    measurementId: 'G-6HXH0CBJQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeN-kiD3E3M9YMrJpWVOO1uiKDGKWm2QY',
    appId: '1:476261170587:android:92141b5a85900b593b753e',
    messagingSenderId: '476261170587',
    projectId: 'vidabrasilapp-cfab9',
    storageBucket: 'vidabrasilapp-cfab9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-esg_ciExgSOu6XJ1TubM6RYhBUp-q1g',
    appId: '1:476261170587:ios:757fc9aec15badd23b753e',
    messagingSenderId: '476261170587',
    projectId: 'vidabrasilapp-cfab9',
    storageBucket: 'vidabrasilapp-cfab9.appspot.com',
    iosBundleId: 'com.example.appHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-esg_ciExgSOu6XJ1TubM6RYhBUp-q1g',
    appId: '1:476261170587:ios:757fc9aec15badd23b753e',
    messagingSenderId: '476261170587',
    projectId: 'vidabrasilapp-cfab9',
    storageBucket: 'vidabrasilapp-cfab9.appspot.com',
    iosBundleId: 'com.example.appHotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPaGkzO8CxTeXKcUopp-zIaSmhGBPatos',
    appId: '1:476261170587:web:960aec64982955853b753e',
    messagingSenderId: '476261170587',
    projectId: 'vidabrasilapp-cfab9',
    authDomain: 'vidabrasilapp-cfab9.firebaseapp.com',
    storageBucket: 'vidabrasilapp-cfab9.appspot.com',
    measurementId: 'G-2QJN0VXGV9',
  );
}
